name: Deploy Astro site to Pages Test

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  deploy:
    uses: area44/workflow-hub/.github/workflows/astro.yml@main
    with:
      run_build: false
